# Generated by Django 2.2.16 on 2022-08-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220825_1242'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='user can not follow himself',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='author',
            new_name='following',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'following'), name='user can not follow himself'),
        ),
    ]
